// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1u36i97kjNAXK1tTsml6_HpFBYnUBdBQ',
    appId: '1:414101353176:web:a9c93048fb00ccfd429dad',
    messagingSenderId: '414101353176',
    projectId: 'test-notifications-f6476',
    authDomain: 'test-notifications-f6476.firebaseapp.com',
    storageBucket: 'test-notifications-f6476.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX4xs5A-ixlc4mhvFPgyBZ93lfQY95OIc',
    appId: '1:414101353176:android:b06c8144f88493e4429dad',
    messagingSenderId: '414101353176',
    projectId: 'test-notifications-f6476',
    storageBucket: 'test-notifications-f6476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDHWm_RArcJrpLojmiVAvniM6pnXY_Co',
    appId: '1:414101353176:ios:ddfe11472a818115429dad',
    messagingSenderId: '414101353176',
    projectId: 'test-notifications-f6476',
    storageBucket: 'test-notifications-f6476.firebasestorage.app',
    iosBundleId: 'com.example.testNotifications',
  );
}
